# Generated by Django 3.0.5 on 2020-07-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='par_event',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
