# Generated by Django 3.2.9 on 2021-12-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_email_par_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkExcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_sheet', models.FileField(upload_to='excel/')),
            ],
        ),
    ]
